### ISSUE TITLE
Go get on pi zero w fails

### ISSUE THREAD

**Issue by LeGaryGary** [charithe/porcupine-go#1]
After cloning the Porcupine repo and moving the libs and includes into /usr/local/... running the command:
`go get github.com/charithe/porcupine-go`
fails with the error:
`go/src/github.com/charithe/porcupine-go/porcupine.go:131:21: type [1073741823]*_Ctype_char too large`

This is on the raspberry pi zero w running raspian stretch

**Comment by charithe** [comment]
I suspect that the problem is due to the hacky way that  C `char**` types have to be handled in Go code. I have pushed a patch that could _potentially_ fix this problem but unfortunately I don't have a working Raspberry Pi available to fully test it. Could you try again by running `go get -u github.com/charithe/porcupine-go` on your RPi and let me know if it works?

**Comment by LeGaryGary** [comment]
Thanks! It works perfectly now :)

**Comment by charithe** [comment]
I am glad that worked out.
